# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.6/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "D:/Libraries/Documents/Git/In64/FPGA/SD_card_test.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "d:/Libraries/Documents/Git/In64/FPGA/SD_card_test.srcs/sources_1/ip/mig_v3_92_0/coregen.cgc"

set ipFile "d:/Libraries/Documents/Git/In64/FPGA/SD_card_test.srcs/sources_1/ip/mig_v3_92_0/mig_v3_92_0.xco"

set ipName "mig_v3_92_0"

set vlnv "xilinx.com:ip:mig:3.92"

set cgPartSpec "xc6slx45-3csg324"

set bomFilePath "d:/Libraries/Documents/Git/In64/FPGA/SD_card_test.srcs/sources_1/ip/mig_v3_92_0/pa_cg_bom.xml"

set hdlType "VHDL"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

# configure the IP
set result [source "c:/Xilinx/14.6/ISE_DS/PlanAhead/scripts/pa_cg_config_core.tcl"]

exit $result

